name: Release

on:
  release:
    types: [ published ]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:${{ github.ref_name }}
            ${{ github.repository }}:latest
          build-args: |
            GOPROXY=https://goproxy.io,direct

  release-binary:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.13

    - name: Package
      run: |
        make fabctl
        mv _output fabctl
        tar -cvzf fabctl-${{ github.ref_name }}-linux-amd64.tar.gz fabctl

    - name: Uploading assets...
      uses: softprops/action-gh-release@v1
      with:
        files: |
          fabctl-*.tar.gz